build-job:
  stage: build
  script:
    - echo "Building s21_cat and s21_grep"
    - cd src/cat && make all
    - cd ../grep && make all
  tags:
    - test

test-job:
  stage: test
  script:
    - echo "Testing style"
    - cppcheck src/cat/*.c src/grep/*.c
    - cp materials/linters/.clang-format src/.clang-format
    - clang-format -n src/cat/*.c src/grep/*.c
    - rm src/.clang-format
  tags:
    - test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  tags:
    - test
