build-job:
  stage: build
  script:
    - echo "Building s21_cat and s21_grep"
    - cd src/cat && make s21_cat
    - cd ../grep && make s21_grep
  tags:
    - test

test-job:
  stage: test
  script:
    - echo "Testing style"
    - cppcheck src/cat/*.c src/grep/*.c
    - cp materials/linters/.clang-format src/.clang-format
    - clang-format -n src/cat/*.c src/grep/*.c
    - if [[ $? ]]; then
    - exit 1; fi
    - rm src/.clang-format
  tags:
    - test

test-job2:
  stage: test
  script:
    - echo "Testing s21_cat and s21_grep"
    - code1=$(cd src/cat && make s21_cat_tests)
    - if [[ code1]]; then
    - echo "cat tests failed"; exit 1
    - else
    - echo "cat tests succeeded"; fi
    - code2=$(cd ../grep && make s21_grep_tests)
    - if [[ code2]]; then
    - echo "grep tests failed"; exit 1 
    - else
    - echo "grep tests succeeded"; fi

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  tags:
    - test
