build-job:
  stage: build
  script:
    - echo "Building s21_cat and s21_grep"
    - cd src && make all
  tags:
    - test

test-job:
  stage: test
  script:
    - echo "Testing style"
    - cd src && cppcheck *.c *.h
    - cp materials/linters/.clang-format src/.clang-format
    - cd src && clang-format -n *.c *.h tests/*.c
    - rm src/.clang-format1
  tags:
    - test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  tags:
    - test
