build-job:
  stage: build
  script:
    - echo "Building s21_cat and s21_grep"
    - cd src && make all
  artifacts:
    paths:
      - src/artifacts/build
    expire_in: 30 days
  tags:
    - test

test-style:
  stage: test
  script:
    - echo "Testing style"
    - cppcheck src/*.c
    - cp materials/linters/.clang-format src/.clang-format
    - clang-format -n src/*.c
    - if [ $? -ne 0 ]; then
    - exit 1; fi
    - rm src/.clang-format
  tags:
    - test

test-job:
  stage: test
  script:
    - echo "Testing s21_cat and s21_grep"
    - cd src
    - code1=$(bash tests/s21_cat_tests.sh)
    - if [ "$code1" -ne 0 ]; then
    - echo "cat tests failed"; exit 1
    - else
    - echo "cat tests succeeded"; fi
    - code2=$(bash tests/s21_grep_tests.sh)
    - if [ "$code2" -ne 0 ]; then
    - echo "grep tests failed"; exit 1 
    - else
    - echo "grep tests succeeded"; fi
  tags:
    - test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  tags:
    - test
