build-job:
  stage: build
  script:
    - echo "Building s21_cat and s21_grep"
    - cd src && make all
  tags:
    - test

test-style:
  stage: test
  script:
    - echo "Testing style"
    - cppcheck src/*.c
    - cp materials/linters/.clang-format src/.clang-format
    - clang-format -n src/*.c
    - if [[ "$?" != "0" ]]; then
    - exit 1; fi
    - rm src/.clang-format
  tags:
    - test

test-job:
  stage: test
  script:
    - echo "Testing s21_cat and s21_grep"
    - code1=$(cd src && make s21_cat_tests)
    - if [[ "$code1" != "0" ]]; then
    - echo "cat tests failed"; exit 1
    - else
    - echo "cat tests succeeded"; fi
    - code2=$(make s21_grep_tests)
    - if [[ "$code2" != "0" ]]; then
    - echo "grep tests failed"; exit 1 
    - else
    - echo "grep tests succeeded"; fi
  tags:
    - test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  tags:
    - test
