build-job:
  stage: build
  script:
    - echo "Building s21_cat and s21_grep"
    - cd ~/C3_SimpleBashUtils-0/src && make all
  tags:
    - test

test-job:
  stage: style
  script:
    - echo "Testing style"
    - cd ~/C3_SimpleBashUtils-0/src && cppcheck *.c *.h
    - cp ~/C3_SimpleBashUtils-0/materials/linters/.clang-format ~/C3_SimpleBashUtils-0/src/.clang-format
    - cd ~/C3_SimpleBashUtils-0/src && clang-format -n *.c *.h tests/*.c
    - rm ~/C3_SimpleBashUtils-0/src/.clang-format1
  tags:
    - test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  tags:
    - test
